configType: "" # "windows" or "linux"

windows:
  dotfiles:
    path: ""
    configfiles:
      vscode:
        pathinrepo: ""
        settings: ""
        keybindings: ""
      wezterm:
        pathinrepo: ""
        config: ""

  obsidian:
    vaultpath: ""

linux:
  dotfiles:
    path: ""
